spring:
  datasource:
    url: jdbc:mysql://db:3306/sjp_db
    username: sjp_user
    password: sjp_pass
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
server:
  port: 8080